<div class="w-100 position-relative" style="overflow-y: hidden;">
  <figure class="w-100 p-0 m-0" style="max-height: 200px; overflow-y: hidden;">
    {{ image_tag('images/banner.png', {
      alt: 'Banner',
      width: '100%',
    }) }}
  </figure>
  <h1 class="m-auto position-absolute text-center" style="color: #fff; top: 0; bottom: 0; left: 0; right: 0; max-height: 59px;">
    <i class="fas fa-plane"></i>
    {{ page.title }}
  </h1>
</div>